### ISSUE TITLE
Differentiate partial and full jsons

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#11]
I would suggest to differentiate between full jsons and patch jsons in a way that makes it easy to distinguish them from the outside. So one does not accidentally use the wrong json when modding and the use of a json is clear.

Suggestions are as follows

# Folders
put them in different folders data/ -> full jsons and data_patches/ -> partial jsons

```
\BATTLETECH\Mods\
    \MyModDirectory\
        \data\weapon\
            Weapon_Autocannon_AC5_5-UltraDmg.json

        \data_patches\weapon\
            Weapon_Autocannon_AC5_0-Stock.json
```

# Extension names
An alternative would be to use another file extension for partial jsons, e.g. .patch.json . That would allow data to stay in the same folder

```
\BATTLETECH\Mods\
    \MyModDirectory\
        \data\weapon\
            Weapon_Autocannon_AC5_5-UltraDmg.json
            Weapon_Autocannon_AC5_0-Stock.patch.json
```

**Comment by Mpstark** [comment]
Current plan is that this is specified in `ModDef.ManifestEntry` with implicitly loaded entries having their own defaults.

I believe HBS's folder structure has some cases in which manifest type is not based on what folder it is in. This information is provided in the `VersionManifest.csv` instead and since we're not loading from a .csv, the `\data\` folder mirror will have to contain partial json to merge onto base json. If the base game doesn't have the file, the file simply will be skipped.

The behavior of a mirrored directory only containing entries that are also contained in the base game is well established in modding.

The other implicitly loaded directories, pluralized type name will have the opposite approach, these will be assumed to be whole files that add to the manifest or replace existing manifest entries if their ids match. Since type for each folder is well defined, there is no confusion.

**Comment by CptMoore** [comment]
I'm unsure you got my point, my difficulty lies in quickly differentiating patches and full replacement jsons and knowing what is what at a glance without having to read and memorize the complete readme..

E.g. by naming the data folder data_patches I know that this is not the place to put full jsons...
by using e.g. data_new/chassisDef/ for full jsons its clear for that jsons below data_new should contain everyting.

My main point is not about where to put things, but how to name them.

**Comment by Mpstark** [comment]
As a side note, I've decided to load implicitly the `\MyMod\StreamingAssets\` instead, because this then encompasses all of the files in the `VersionManifest.csv` file.

I've read, walked away, and then re-read the issue thread. I believe that this clarifies my current position:

The current plan is for ModTek to *assume that all json placed in the `\MyMod\StreamingAssets\` directory to be "partial" json* that will merge into an existing base file. A reasonable default for array merging will need to be chosen based on what doens't break HBS's json for reasonable expectations.

If a modder wants to instead *replace* the base files, they would specify so in their `mod.json` file.

Obviously none of this is actually written yet. and is subject to change.

**Comment by CptMoore** [comment]
ok let me summarize as I understood what you wrote...

this contains partial jsons:
\BATTLETECH\Mods\
    \MyModDirectory\
        \StreamingAssets\
            \data
                \weapon\
                    Weapon_Autocannon_AC5_5-UltraDmg.json

anything outside of that can be full jsons but should be declared in the manifest, e.g.
\BATTLETECH\Mods\
    \MyModDirectory\
        \coolstuff\
              Weapon_Autocannon_AC5_0-Stock.json

using the manifest, one is always sure about the type that is imported. that also avoids the issue of having to predefine directories for all json and other asset types.

Regarding the array handling, replace is the way to go, Otherwise one has to start index counting, and that won't work if the source material changes order for some reason. Also a replace algorithm is easier to understand than a merge algorithm.
Make me a partial json that removes a hardpoint from the head, and adds one to the left arm, only possible with replace right?
```
    "Locations": [
        {
            "Location": "Head",
            "Hardpoints": [
                {
                    "WeaponMount": "AntiPersonnel",
                    "Omni": false
                },
                {
                    "WeaponMount": "Energy",
                    "Omni": false
                }
            ],
            "Tonnage": 0,
        },
        {
            "Location": "LeftArm",
            "Hardpoints": [],
            "Tonnage": 0,
        },
```


Ok my issue with the whole topic is much much smaller then you think I believe:
I expect a json under the StreamingAssets to be a full json just looking at the naming. Yes one can define it to contain partial jsons, but nothing tells me it does as part of the structure or the name of the file itself.
I just want to see a self describing term somewhere in the filesystem telling me those are not normal json copies (full jsons) but should be used only for patching!

StreamingAssets_diff/
StreamingAssets_patches/
does not perfectly say that either, you could mean a diff in file structure and not that jsons are partial jsons.. 

using an extension makes it clear
Weapon_Autocannon_AC5_0-Stock.patch.json
or
Weapon_Autocannon_AC5_0-Stock.diff.json
or
Weapon_Autocannon_AC5_0-Stock.partial.json

maybe I'm overthinking it here, again its just a small issue.

**Comment by Mpstark** [comment]
Assuming replace array handling, json merging in the way that I'm envisioning is nearly a superset in behavior of simply replacing the file in the manifest, excepting that entries are not removed unless directly told that they are null. I.E. if a full file is dropped in and loaded as a partial json, the merge has nearly identical results as replacing.

Looking at the current modding scene, most json mods are simply tweaks to things distributed in whole files that replace the game files or are entirely new files. Encouraging the behavior of shipping partial by making it the default is a decent side effect, as well as having a clear chain of events that a user expects:

* Manifest loads from base json
* Mod1 merged
* Mod2 merged
* Mod3 merged

If whole files are shipped by a modder and are placed in the implicit StreamingAssets path but are assumed to be merges, this process is the same. Say Mod2 does so; it simply overwrites all Mod1 changes back to whatever base was at Mod2 ship time.

However, if a mod distributes a whole file that replaces the manifest entry path that the game loads it from, the chain of events is a little odd in the case of load order.

* Manifest loads from Mod2
* Mod1 not merged because it patches base json
* Mod3 merged

**Comment by Mpstark** [comment]
In addition, I'd like to be clear -- we're not *really* patching the json, we're merging on top of it.

I'd like to include a much more robust solution for patching using an industry-adopted solution. I haven't put much research into it.

**Comment by CptMoore** [comment]
> Encouraging the behavior of shipping partial by making it the default is a decent side effect

I agree. What mechanisms do we have so that the user does not start dumping full jsons in the StreamingAssets folder?
My suggestions were focusing on visual cues, but can guards be put in place that are enforced?

> Assuming replace array handling, json merging in the way that I'm envisioning is nearly a superset in behavior of simply replacing the file in the manifest

Unless we find and implement that "industry-strength" solution, I don't see what else would be better. All other variants MergeArrayHandling is providing are also very situational. A mod trying to fix hardpoints will not be able to use ModTek it its current form with the vision you describe using any of the MergeArrayHandling variants. In case of array replace only the array content but not the whole json have to replaced. In all other array variants I can see them having to provide full jsons in some cases.

**Comment by Mpstark** [comment]
I agree replace array handling is a good thing, that's why I assumed that it would be the case in my examples. Sorry if I wasn't clear.

> What mechanisms do we have so that the user does not start dumping full jsons in the StreamingAssets folder?

Nothing -- it should _generally_ work and according to load order, when their mods "turn" to merge json comes up, it'll just merge everything.

**Comment by CptMoore** [comment]
ok, lets close this ticket and make a new one for handling array merging and/or finding a better or alternative merge/patch solution?
