### ISSUE TITLE
Move Manifest information to its own file

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#15]
I would like the mod.json to stay short, should be basically a summary only, so a manifest.json file would allow to keep it short even on large projects.

thoughts?

**Comment by Mpstark** [comment]
Since manifest is an optional field in mod.json, only mods that contain manifest entries will need to include this field. Implicit loading will work somewhat like default manifest entries.

Because of this, I believe that most mods will not need to include manifest at all in their mod.json file and when they do have to, it'll be rather short. You can specify paths to folders that contain only a particular type of entry as well.

**Comment by Mpstark** [comment]
Reopening so that others can chime. I'm not 100% on the etiquette of tickets like this -- def wasn't intending to be accidentally rude.

**Comment by CptMoore** [comment]
If others would be chiming in, i would leave these open and add labels that say discussion.

That said.. here I think you reasoning sounds ok, so close would fit.

usually its the guy creating a ticket that also closes it, but dont know about github projects myself, there I think the people in charge close in order to keep the ticket count down.
