### ISSUE TITLE
Version 0.1.0-alpha test report: SimGameConstants changes not applied.

### ISSUE THREAD

**Issue by TimeDiver0** [Mpstark/ModTek#29]
Original issue resolved, new one up in its place. Described further below.

**Comment by TimeDiver0** [comment]
Attempt to override '\StreamingAssets\data\backgrounds\background_career_mercenary.json' is not reflecting in-game.

Edited 'background_career_mercenary.json' file:

{
"Results" : {
"Scope" : "Commander",
"Requirements" : null,
"AddedTags" : {
"items" : [
"commander_career_mercenary"
],
"tagSetSourceFile" : ""
},
"RemovedTags" : null,
"Stats" : [
{
"typeString" : "System.Int32",
"name" : "Piloting",
"value" : 10,
"set" : "true",
"valueConstant" : ""
},
{
"typeString" : "System.Int32",
"name" : "Gunnery",
"value" : 10,
"set" : "true",
"valueConstant" : ""
},
{
"typeString" : "System.Int32",
"name" : "Tactics",
"value" : 10,
"set" : "true",
"valueConstant" : ""
},
{
"typeString" : "System.Int32",
"name" : "Guts",
"value" : 10,
"set" : "true",
"valueConstant" : ""
}
],
"Actions" : null,
"ForceEvents" : null,
"TemporaryResult" : false,
"ResultDuration" : 0
},
}

Kept the array completely intact, as per the Special JSON Handling section of 'The mod.json Format' page.

Duplicated the paths exactly as shown in the 'Anatomy of a ModTek Mod' example:

'<Installation_Folder>\BATTLETECH\Mods\Custom\StreamingAssets\Data\backgrounds\background_career_mercenary.json'

Mod.json contents:

{
"Name": "Custom",
"Version": "1.0.0",
"Enabled": true,
}

ModTek.log results:

ModTek -- 5/9/2018 9:40:15 PM
9:40:16 PM - Loading Custom
New Entry: Custom\StreamingAssets\Data\backgrounds\background_career_mercenary.json

9:40:16 PM - Adding in mod manifests!
Custom:

9:40:16 PM - Adding in mod manifests!
Custom:

**Comment by Mpstark** [comment]
The StreamingAssets folder uses the default Path behavior to see if the path of a file is indicated in the version manifest. If the full resolved paths match, it does the merge.

You've got an problem on your `Custom\StreamingAssets\data\SimGameConstants\SimGameConstants.json` path, it should be `Custom\StreamingAssets\data\simGameConstants\SimGameConstants.json`.

Paths are generally case-sensitive.

I just tried a simple mod that changes that file. It doesn't currently work because the default `Custom\StreamingAssets\data\simGameConstants\SimGameConstants.json` file contains invalid JSON. I will use my backup strategy of using their code to deserialize their json and then serialize *that* to hopefully proper real JSON and then patch the result.

**Comment by TimeDiver0** [comment]
...yeah, that one's _entirely_ on me.

I notice the whole 'Data' vs 'data' case-sensitivity, and then completely manage to **not** notice the same case-sensitivity with 'SimGameConstants' (the folder).

*head--->desk, closes Issue*
