### ISSUE TITLE
Adjust DB Location for Modded Content

### ISSUE THREAD

**Issue by Mpstark** [Mpstark/ModTek#37]
Same as the saves, since if the vanilla game gets modded content out of the db and tries to load it when it isn't installed or enabled, it breaks.

**Comment by CptMoore** [comment]
i assume you are talking about the mmdb? I think its regenerated each app start

see
metadataDatabase.Rebuild(true);
called from
Awake() which seems to be a games main method

SimGameState is the thing that is related to save games, and there the Rehydrate method replaces all fields about the game state based on what is found in the same game.. pilots.. mechDefs..

By hooking in after Rehydrate , I was able to add pilots to a save no problem.

I also think mechlab settings for skirmish are saved in a settings file (e.g. settings_cloud.sav), there of course one has again copies of mechdefs etc.. which makes it hard to uninstall mods since one can only overwrite those settings by going into a skirmish mechlab again and doing something to save the settings.

Did I miss something? Did you mean something else?

**Comment by Mpstark** [comment]
The db is not rebuilt every load. If something is inserted into the DB, it is persistent. You can force a rebuild of the DB by deleting it, or by forcing a hot reload. It takes a long, long time.

My plan with the DB is to maintain a mod `MetadataDatabase.db` in a separate location then the vanilla one, and track mod additions. 

Yes, the hydrate/rehydrate methods are from loading into a save -- it may be possible to hijack that and remove old modded content that doesn't exist anymore, I haven't really looked that much into it.

**Comment by CptMoore** [comment]
> It takes a long, long time.

oh ok, so keeping up the cache between app starts to avoid long loading times and try to build up a cache invalidation mechanism, now I understand

thx for all the explanations

**Comment by Mpstark** [comment]
This is now in ModTek 0.2.0
