### ISSUE TITLE
Use HBS.Logging for better integration into BattleTech logging

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#9]
would also apply to BTML

in order for the logs to appear in BATTLETECH\BattleTech_Data\output_log.txt that is already used by BattleTech, one should reuse the existing logging infrastructure

use the HBS logger to log into output_log.txt
```
var logger = HBS.Logging.Logger.GetLogger(Name);
logger.Log("this is a log");
```

then additional log files for your logger can be added with the following:
```
            if (!string.IsNullOrEmpty(settings.additionalLogFile))
            {
                var logFilePath = Path.Combine(Directory, logFile);
                //HBS.Logging.Logger.SetLoggerLevel(Name, LogLevel.Debug);
                var appender = new FileLogAppender(logFilePath, FileLogAppender.WriteMode.INSTANT);
                HBS.Logging.Logger.AddAppender(Name, appender);
            }
```

that way one have a combined log for checking behavior against everything running in the app, and another log just for the mod.

**Comment by Mpstark** [comment]
I personally like the idea of separate logs for separate things, but I can see the benefit for handling some things through this mechanism since mods already will taint the log if they throw an exception during a Harmony patch.

I'll think about it -- if anyone else has an opinion on this, leave a comment on this issue.
